### ISSUE TITLE
compare argonnite with jellyfish

### ISSUE THREAD

**Issue by sebhtml** [GeneAssembly/biosal#246]
# Parameters

k = 24, 43, 63, 81
# Datasets
## Dataset SAMN02402663

Sample: http://www.ebi.ac.uk/biosamples/sample/SAMN02402663

Sequencing sample: http://www.ebi.ac.uk/ena/data/view/SRS565204

Blobs:

ftp.sra.ebi.ac.uk/vol1/fastq/SRR118/000/SRR1181090/SRR1181090_1.fastq.gz
ftp.sra.ebi.ac.uk/vol1/fastq/SRR118/000/SRR1181090/SRR1181090_2.fastq.gz
ftp.sra.ebi.ac.uk/vol1/fastq/SRR118/001/SRR1181121/SRR1181121_1.fastq.gz
ftp.sra.ebi.ac.uk/vol1/fastq/SRR118/001/SRR1181121/SRR1181121_2.fastq.gz

Meta:

http://www.ebi.ac.uk/ena/data/warehouse/filereport?accession=SRP039325&result=read_run&fields=study_accession,secondary_study_accession,sample_accession,secondary_sample_accession,experiment_accession,run_accession,scientific_name,instrument_model,library_layout,fastq_ftp,fastq_galaxy,submitted_ftp,submitted_galaxy,col_tax_id,col_scientific_name,sra_ftp,sra_galaxy
## Dataset meta1

-rw-rw-r-- 1 seb seb 20G Jun 18 15:46 /home/seb/dropbox/GPIC.1424-1.1371.fastq
## Dataset meta2

20G     datasets/Iowa_Continuous_Corn/GPIC.1424-1.1371.fastq
22G     datasets/Iowa_Continuous_Corn/GPIC.1424-2.1371.fastq
22G     datasets/Iowa_Continuous_Corn/GPIC.1424-3.1371.fastq
23G     datasets/Iowa_Continuous_Corn/GPIC.1424-4.1371.fastq
20G     datasets/Iowa_Continuous_Corn/GPIC.1424-5.1371.fastq
22G     datasets/Iowa_Continuous_Corn/GPIC.1424-6.1371.fastq
22G     datasets/Iowa_Continuous_Corn/GPIC.1424-7.1371.fastq
21G     datasets/Iowa_Continuous_Corn/GPIC.1425-1.1367.fastq
24G     datasets/Iowa_Continuous_Corn/GPIC.1425-2.1367.fastq
24G     datasets/Iowa_Continuous_Corn/GPIC.1425-3.1367.fastq
23G     datasets/Iowa_Continuous_Corn/GPIC.1425-4.1367.fastq
23G     datasets/Iowa_Continuous_Corn/GPIC.1425-5.1367.fastq
23G     datasets/Iowa_Continuous_Corn/GPIC.1425-6.1367.fastq
22G     datasets/Iowa_Continuous_Corn/GPIC.1425-7.1367.fastq
9.2G    datasets/Iowa_Continuous_Corn/GPIC.649-4.899.fastq
11G     datasets/Iowa_Continuous_Corn/GPIC.868-1.1053.fastq
11G     datasets/Iowa_Continuous_Corn/GPIC.868-2.1053.fastq
11G     datasets/Iowa_Continuous_Corn/GPIC.868-3.1053.fastq
11G     datasets/Iowa_Continuous_Corn/GPIC.868-4.1053.fastq
11G     datasets/Iowa_Continuous_Corn/GPIC.868-5.1053.fastq
11G     datasets/Iowa_Continuous_Corn/GPIC.868-6.1053.fastq
14G     datasets/Iowa_Continuous_Corn/GPIC.895-5.1070.fastq
14G     datasets/Iowa_Continuous_Corn/GPIC.895-6.1070.fastq
14G     datasets/Iowa_Continuous_Corn/GPIC.895-7.1070.fastq
12G     datasets/Iowa_Continuous_Corn/HTHO.1209-1.1231.fastq
13G     datasets/Iowa_Continuous_Corn/HTHO.1209-2.1231.fastq
9.5G    datasets/Iowa_Continuous_Corn/HTHO.1300-6.1364.fastq
22G     datasets/Iowa_Continuous_Corn/HTHO.1429-2.1388.fastq
## App 1

argonnite (energy branch, commit: ###########)
## App 2

jellyfish 2.1.3 ftp://ftp.genome.umd.edu/pub/jellyfish/jellyfish-2.1.3.tar.gz
http://www.cbcb.umd.edu/software/jellyfish/jellyfish-manual-1.1.pdf
# Hardware
## For SAMN02402663 and meta1

32 cores (model name      : QEMU Virtual CPU version 1.0), 28 available.
1 TiB available
## For meta2

http://beagle.ci.uchicago.edu/
# Output:

coverage distribution (columns: coverage, frequency)

**Comment by sebhtml** [comment]
with -c 3 (from the manual), jellyfish does not output all the kmers

```
[seb@sal jellyfish-comparison]# cat meta1-jellyfish.sh
#!/bin/bash

#./jellyfish merge -o merge-meta1-43-jellyfish.jf count-meta1-43-jellyfish*

time (
./jellyfish count -m 43 --canonical -o count-meta1-43-jellyfish -c 3 -s 10000000 -t 32 GPIC.1424-1.1371.fastq
./jellyfish histo count-meta1-43-jellyfish > histo-meta1-43-jellyfish.txt
) | tee log-meta1-43-jellyfish.txt
```

[seb@sal jellyfish-comparison]# cat histo-meta1-43-jellyfish.txt | awk '{ sum+=$1 \* $2} END {print sum}'
5217016526

[seb@sal dropbox]# wc -l GPIC.1424-1.1371.fastq  
362454176 GPIC.1424-1.1371.fastq

irb(main):002:0> 362454176 / 4 \* (100 - 43 + 1)
=> 5255585552

**Comment by sebhtml** [comment]
With -c 7 (the default value), it still misses a lot of kmers 

[seb@sal jellyfish-comparison]# cat meta1-jellyfish-c-7.sh
#!/bin/bash

#./jellyfish merge -o merge-meta1-43-jellyfish.jf count-meta1-43-jellyfish*

time (
./jellyfish count -m 43 --canonical -o count-meta1-43-jellyfish7 -c 7 -s 10000000 -t 32 GPIC.1424-1.1371.fastq
./jellyfish histo count-meta1-43-jellyfish7 > histo-meta1-43-jellyfish7.txt
) | tee log-meta1-43-jellyfish7.txt
[seb@sal jellyfish-comparison]# cat histo-meta1-43-jellyfish7.txt | awk '{ sum+=$1 \* $2} END {print sum}'
5217016526

irb(main):001:0> 5255585552 - 5217016526
=> 38569026

**Comment by sebhtml** [comment]
# Results

| Dataset | Kmer length | App | Walltime |
| --- | --- | --- | --- |
| meta2 | 43 | argonnite | x |
| meta1 | 43 | argonnite | 16m10.363s (5a62b89ee) ~~16m45.539s (be2f4e044)~~ ~~21m33.976s 0c38c2a5d~~ ~~23m37.807s 6cfaa5a (4 \* 7 threads)~~ ~~31m28.282s (4 \* 7 threads)~~ ~~39m1.457s (4 \* 7 threads)~~ ~~42m2.639s (4 \* 7 threads)~~ ~~44m0.562s (4 \* 7 threads)~~ |
| meta1 | 43 | jellyfish | 26m52.854s (28 threads) |

**Comment by levinas** [comment]
Is argonnite still running?

**Comment by sebhtml** [comment]
@levinas I am still tuning things. current walltime for argonnite is 58m17.737s. But load analysis shows that there is a bottleneck in actors. I'll send you an email with details

**Comment by sebhtml** [comment]
now at 50m25.364s

**Comment by sebhtml** [comment]
with 32 threads 119m55.401s, meta1, argonnite

**Comment by sebhtml** [comment]
jellyfish on meta1 with 32 cores 24m50.777s

**Comment by sebhtml** [comment]
argonnite with 4 \* 7 on meta1 44m0.562s
argonnite with 1 \* 28 on meta1 104m8.599s
argonnite with 7 \* 4 on meta1 xxx

**Comment by sebhtml** [comment]
meta1 argonnite 4 \* 7 1e5e632104a7be2b722ec5 106m21.015s

**Comment by sebhtml** [comment]
99ce92748c16f68549de84 meta1 argonnite 4 \* 7 -> xxx

**Comment by sebhtml** [comment]
731597a395a6adb74fc34f01d09e39ede619f013 with 2-bit encoding (75% memory usage reduction):
./scripts/development/run-argonnite-4-7.sh
33m46.226s

**Comment by sebhtml** [comment]
8097361ec29277390d01187325ac5b38f361a03b
with patch:

```
boisvert@prologcs:~/biosal$ git diff
diff --git a/applications/argonnite_kmer_counter/argonnite.c b/applications/argonnite_kmer_counter/argonnite.c
index 60213a0..4ee9e85 100644
--- a/applications/argonnite_kmer_counter/argonnite.c
+++ b/applications/argonnite_kmer_counter/argonnite.c
@@ -77,7 +77,8 @@ void argonnite_init(struct bsal_actor *actor)
     /* the number of input sequences per I/O block
      *
      */
-    concrete_actor->block_size = 4096;
+    /*concrete_actor->block_size = 4096;*/
+    concrete_actor->block_size = 8192;
     /*concrete_actor->block_size = 2048;*/

     concrete_actor->configured_actors = 0;
diff --git a/patterns/aggregator.c b/patterns/aggregator.c
index 01377fc..e6b39b3 100644
--- a/patterns/aggregator.c
+++ b/patterns/aggregator.c
@@ -58,7 +58,7 @@ void bsal_aggregator_init(struct bsal_actor *self)
     bsal_vector_init(&concrete_actor->customers, sizeof(int));
     bsal_vector_init(&concrete_actor->buffers, sizeof(struct bsal_dna_kmer_block));

-    concrete_actor->customer_block_size = 512;
+    concrete_actor->customer_block_size = 1024;
     concrete_actor->flushed = 0;

     bsal_dna_codec_init(&concrete_actor->codec);
diff --git a/storage/sequence_store.c b/storage/sequence_store.c
index 117f120..5bf1723 100644
--- a/storage/sequence_store.c
+++ b/storage/sequence_store.c
@@ -319,7 +319,7 @@ void bsal_sequence_store_ask(struct bsal_actor *self, struct bsal_message *messa
                         concrete_actor->received, concrete_actor->expected,
                         concrete_actor->reservation_producer);
     }
-    block_size = 256;
+    block_size = 1024;

     if (!concrete_actor->iterator_started) {
         bsal_vector_iterator_init(&concrete_actor->iterator, &concrete_actor->sequences);

```
