### ISSUE TITLE
add an actor for reading FASTA files

### ISSUE THREAD

**Issue by levinas** [GeneAssembly/biosal#247]
for DNA and protein sequences?

**Comment by sebhtml** [comment]
Yes.
We can decouple reading from storing.

**Comment by sebhtml** [comment]
@hubot says: implemented in commit https://github.com/sebhtml/biosal/commit/9cedc511fc88098afc9bd387a24715f8623fe5b2 by @sebhtml !

**Comment by levinas** [comment]
Great.

**Comment by sebhtml** [comment]
thanks !

It is not an actor however, it is a driver used by input_stream:

Code path:

input_stream -> input_proxy -> input_format -> fasta_input -> buffered_reader -> raw_buffered_reader
