### ISSUE TITLE
Message size percentile

### ISSUE THREAD

**Issue by huyba** [GeneAssembly/biosal#570]
Hi,

I need know message size percentile in communication carrying by Thorium i.e. what is max size, min size, average size, sizes that 25%, 50% (median) and 75% number of messages below, to estimate how much benefit we can get from using PAMI and to create buffer size appropriately.

Thanks,

Huy.

**Comment by sebhtml** [comment]
related: PAMI #453

**Comment by sebhtml** [comment]
With -enable-transport-profiler:

http://pastebin.com/xjrCyWa2

I checked and the helper functions to compute percentiles don't support frequency distribution right now, only vector of values are supported. So we will need to add that if we want percentiles for buffer sizes.

**Comment by sebhtml** [comment]
@hubot says: implemented in commit https://github.com/sebhtml/biosal/commit/deecca11b47cfc46a200f57eaaee0636b15ff75f by @sebhtml !

**Comment by huyba** [comment]
Thanks for the byte count and frequency. I plotted the quadtile and 
historgram based on your numbers - mainly for fun.

Huy.
