### ISSUE TITLE
Output of spate

### ISSUE THREAD

**Issue by minillinim** [GeneAssembly/biosal#665]
Hey, not really a big issue. How does one interpret the collection of unitig_walker_XXXXX.fasta files? I looked for Docs but I might have been having a slack look.

**Comment by sebhtml** [comment]
They basically contain redundant unitigs (I am currently working on these bits).

These files will disappear at some point, they are just for debugging.

Also, the assembly code is not ready for end users.

Thanks for your kin interest !

**Comment by minillinim** [comment]
No problem,

I'll stop bugging you about it then. I assumed it would be very beta. 
Let me know when you get closer to actual release, I'm more than happy 
to be a guinea pig.

I actually only installed it so I could try work out what was meant by 
the term "genome isolation". I was really interested to see your take 
on attacking this problem at the assembly level.

I really like the work you're doing, we always need better open source 
assemblers. Keep it up.

Mike.

**Comment by sebhtml** [comment]
Thanks !

So far, we have put a lot of time in Thorium (a compute engine based on Hewitt's actor theory).
Now that part works.
