### ISSUE TITLE
Implement synchronous message handling

### ISSUE THREAD

**Issue by sebhtml** [GeneAssembly/biosal#7]

**Comment by sebhtml** [comment]
2e05c3c89162a5ce9afd804dd117efdf8c0bb33e

**Comment by levinas** [comment]
Are you going to push the energy branch? The commit links don't work for me now.

**Comment by sebhtml** [comment]
Sure.

I will send you an email so that you can review changes between

remotes/geneassembly/master and remotes/sebhtml/energy

I will then do a git merge --no-ff --edit and indicate that you did the review.
