### ISSUE TITLE
use BSAL_ACTOR_STOP to kill an actor

### ISSUE THREAD

**Issue by sebhtml** [GeneAssembly/biosal#91]

**Comment by sebhtml** [comment]
@hubot says: implemented in commit https://github.com/sebhtml/biosal/commit/348ebdde932859c60914c6743c5fe2e0015cadab by @sebhtml !

**Comment by leereilly** [comment]
<img src="https://cloud.githubusercontent.com/assets/121322/3152986/33c9fc78-ea95-11e3-8c73-6b413298d924.png" width="50%">

**Comment by sebhtml** [comment]
meh
